### ISSUE TITLE
Omit the last comma on arguments

### ISSUE THREAD

**Issue by smaniotto** [jonatasbaldin/coding-style#1]
Is there any strong reason for that?

For one-liners I omit and for multiple lines I keep:

One-liners:
```python
response = my_func(arg1=1, arg2=2)
```

Multiple lines:
```python
response = my_func(
    arg1=1,
    arg2=2,
    arg3=3,
)
```

Reason:
I do think that omitting is cleaner, but if you have to add an additional argument on the multi lines example, it leads to one removal and one addition on git diff, and this way it's more prone to cause merge conflicts.

**Comment by jonatasbaldin** [comment]
I was thinking more on readability, that last comma makes me think some argument is missing, that something should be there. What you think?

But the git diff is a great point, I did not think about that.

I have mix feelings now.

**Comment by smaniotto** [comment]
Both work. I don't have a strong opinion on this one.

**Comment by jonatasbaldin** [comment]
I guess I'm gonna keep this way so. Thanks!
